from enum import Enum

class RAGStateEnum(Enum):
    INIT = "INIT"
    CLASSIFY_QUERY = "CLASSIFY_QUERY"
    RETRIEVE = "RETRIEVE"
    BUILD_CONTEXT = "BUILD_CONTEXT"
    NUMERIC_PREPROCESS = "NUMERIC_PREPROCESS"
    GENERATE_ANSWER = "GENERATE_ANSWER"
    VALIDATE_CITATIONS = "VALIDATE_CITATIONS"
    FINALIZE_RESPONSE = "FINALIZE_RESPONSE"
    ERROR = "ERROR"
